### ISSUE TITLE
debugMode set false not working

### ISSUE THREAD

**Issue by chipcop106** [hueindahaus/react-messenger-chat-plugin#1]
I had set debugMode={false} but it still shows log events in the console.

**Comment by hueindahaus** [comment]
Hello chipchop! Thank you so much for reaching out. Do you mean the initial console.log on the component props (examplified in the image below)? Otherwise I can't seem to replicate/recreate this issue. Could you provide some images of your arguments/props in to the component + image on the logs, and I will do my best to fix it.

![image](https://user-images.githubusercontent.com/45295311/135839205-355923da-0650-4b4a-9f2a-22bf4b044835.png)

**Comment by hueindahaus** [comment]
I have now fixed the console.log on the props (and also fixed broken height setting)! If that was the issue, please confirm by commenting and I will close the issue after that :). Note: Make sure you update the package to 1.0.7!

**Comment by hueindahaus** [comment]
I will close this issue, and if it the problem persist get back to me!
